"""USA case/module mapping verified from the native mission table."""
CASE_MODULES = {"Boltaire Museum": 1,
 "Boltaire Gem Wing": 2,
 "Max-Security Cells": 3,
 "Rooftop Deathtrap": 4,
 "Asyanica Rooftops": 4,
 "Larger Than Life": 5,
 "Countess's Villa": 7,
 "Glaciara, Ski Slopes": 8,
 "The Mess Hall": 9,
 "Azcotal Alley": 10,
 "Gondola Ascent": 11,
 "Suck and Jive": 11,
 "High-Rollers Casino": 13,
 "The Exercise Yard": 14,
 "High Stakes Room": 15,
 "Venantonio Labs": 16,
 "Venantonio Canals": 17,
 "Madam Butterqwark": 18,
 "Galactic Bolt Reserve": 19,
 "Inside the A-Eye": 20,
 "The Showers": 21,
 "Spaceship Graveyard": 22,
 "Saint Qwark": 23,
 "The Quasar Fields": 24,
 "Prison Breakout!": 25,
 "Dam's Edge, Hydrano": 26,
 "A Fiction Full Of Dollars": 27,
 "Bulkhead Lock": 28,
 "Underwater Bunker": 29,
 "Klunk's Lair": 30,
 "High Impact Treehouse": 31}
