class SACPickups:
    """String constants for weapon/gadget pickup locations"""
    BOLTAIRE_MUSEUM_TIE_A_RANG = "Boltaire (Clank) - Boltaire Museum: Tie-A-Rang Pickup"
    BOLTAIRE_MUSEUM_JET_BOOTS = "Boltaire (Clank) - Boltaire Museum: Jet Boots Pickup"
    BOLTAIRE_MUSEUM_BLACKOUT_PEN = "Boltaire (Clank) - Boltaire Museum: Blackout Pen Pickup"
    BOLTAIRE_MUSEUM_DUAL_LACERATORS = "Boltaire (Clank) - Boltaire Museum: Dual Lacerators Pickup"
    BOLTAIRE_MUSEUM_DUAL_THERM_OPTIC_SHADES = "Boltaire (Clank) - Boltaire Museum: Therm-Optic Shades Pickup"
    ASYANICA_ROOFTOPS_CUFFLINK_BOMB = "Asyanica (Clank) - Asyanica Rooftops: Cufflink Bomb Pickup"
    ASYANICA_ROOFTOPS_OMNI_KEY = "Asyanica (Clank) - Asyanica Rooftops: Omni-Key 5000 Pickup"
    ASYANICA_ROOFTOPS_MINE_LAUNCHER = "Asyanica (Clank) - Asyanica Rooftops: Mine Launcher Pickup"
    AZCOTAL_ALLEY_TANGLEVINE_CARNATION = "Rionosis (Clank) - Azcotal Alley: Tanglevine Carnation Pickup"
    AZCOTAL_ALLEY_BEE_MINE_MK_II = "Rionosis (Clank) - Azcotal Alley: Bee Mine Mk. II Pickup"
    HIGH_ROLLERS_CASINO_HOLO_MONOCLE = "The Paradis Des Tricheurs Casino (Clank) - High-Rollers Casino: Holo-Monocle Pickup"
    VENANTONIO_LABS_BLOWTORCH_BRIEFCASE = "Venantonio (Clank) - Venantonio Labs: Blowtorch Briefcase Pickup"
    MAX_SECURITY_CELLS_SHARDGUN = "Prison Planet (Ratchet) - Max-Security Cells: Shard Gun Pickup"
    MAX_SECURITY_CELLS_WALLOPER = "Prison Planet (Ratchet) - Max-Security Cells: Walloper Pickup"