"""Skill point gameplay requirements: wiki-backed ownership and curated difficulty; see docs/skill-points.md."""
from enum import IntEnum

from .operatives import SACOperatives
from .skillpoints import SACSkillPointLocations as SP


class SkillPointDifficulty(IntEnum):
    EASY = 1
    HARD = 2


# Easy favors short/repeatable actions and forgiving weapon restrictions.
# Hard includes perfect runs, exhaustive objectives, tight timing and score goals.
EASY_SKILL_POINTS = frozenset({
    SP.BOLTAIRE_MUSEUM_FURIOUS_FISTS,
    SP.MAX_SECURITY_CELLS_PLAYING_WITH_FIRE,
    SP.ASYANICA_ROOFTOPS_BLACK_TIE_AFFAIR,
    SP.LARGER_THAN_LIFE_INVERSE_NINJA_LAW,
    SP.LARGER_THAN_LIFE_BLASTER_OVERLOAD,
    SP.GLACIARA_SKI_SLOPES_SMOOTH_MOVES,
    SP.GONDOLA_ASCENT_STEEL_RAIN,
    SP.SUCK_AND_JIVE_CARD_PICKUP,
    SP.SUCK_AND_JIVE_DRESS_FOR_SUCCESS,
    SP.THE_EXERCISE_YARD_INDIAN_BURN,
    SP.VENANTONIO_LABS_ALL_SLIME_MUST_BURN,
    SP.VENANTONIO_LABS_RAMMING_SPEED,
    SP.VENANTONIO_CANALS_EVASIVE_MANEUVERS,
    SP.GALACTIC_BOLT_RESERVE_WITH_INTEREST,
    SP.GALACTIC_BOLT_RESERVE_ANDROIDS_IN_DISGUISE,
    SP.INSIDE_THE_A_EYE_DIA_DE_LOS_MUERTOS,
    SP.THE_SHOWERS_RUBA_DUB_CLUB,
    SP.SAINT_QWARK_PUNCHY,
    SP.SAINT_QWARK_SOUR_VICTORY,
    SP.THE_QUASAR_FIELDS_KILL_THE_ROCK,
    SP.PRISON_BREAKOUT_WHIP_IT_GOOD,
    SP.DAMS_EDGE_HYDRANO_YEEE_HAAAAAW,
    SP.DAMS_EDGE_HYDRANO_SLIPPERY_SLOPE,
    SP.A_FICTION_FULL_OF_DOLLARS_CLEANS_POOLS_TOO,
    SP.UNDERWATER_BUNKER_RUST_PROOF,
    SP.KLUNKS_LAIR_TURN_THE_TABLES,
    SP.KLUNKS_LAIR_PRETTY_GOOD_LIKENESS,
})
HARD_SKILL_POINTS = frozenset({
    SP.BOLTAIRE_MUSEUM_SILENT_NIGHT,
    SP.BOLTAIRE_GEM_WING_PYRRHIC_VICTORY,
    SP.BOLTAIRE_GEM_WING_TRIPLE_PLATINUM,
    SP.MAX_SECURITY_CELLS_STAINLESS_STEEL,
    SP.ROOFTOP_DEATHTRAP_SPEED_DEMON,
    SP.ROOFTOP_DEATHTRAP_PERFECT_CHROME_FINISH,
    SP.ASYANICA_ROOFTOPS_ROBOT_FINDS_NINJA,
    SP.ASYANICA_ROOFTOPS_LIKE_THE_WIND,
    SP.COUNTESS_VILLA_PERFECT_TANGO,
    SP.GLACIARA_SKI_SLOPES_BLACK_DIAMOND,
    SP.GLACIARA_SKI_SLOPES_RINGLEADER,
    SP.THE_MESS_HALL_EMPTY_THE_WARRENS,
    SP.THE_MESS_HALL_ANTAEUS,
    SP.AZCOTAL_ALLEY_MASTER_OF_DISGUISE,
    SP.AZCOTAL_ALLEY_TRASH_TALK,
    SP.AZCOTAL_ALLEY_DEADLY_HANDS,
    SP.HIGH_ROLLERS_CASINO_BEAT_THE_HOUSE,
    SP.THE_EXERCISE_YARD_LAW_CANT_TOUCH_ME,
    SP.HIGH_STAKES_ROOM_LUCKY_SEVENS,
    SP.HIGH_STAKES_ROOM_GADGEBOT_STANDS_ALONE,
    SP.VENANTONIO_CANALS_DEEP_SIX,
    SP.VENANTONIO_CANALS_WAKE_OF_DESTRUCTION,
    SP.VENANTONIO_CANALS_RINGMASTER,
    SP.MADAM_BUTTERQWARK_TWINKLE_TOES,
    SP.MADAM_BUTTERQWARK_MAGNUM_OPUS,
    SP.MADAM_BUTTERQWARK_SOLD_OUT,
    SP.GALACTIC_BOLT_RESERVE_VAULT_VAULT,
    SP.THE_SHOWERS_MODESTY,
    SP.SPACESHIP_GRAVEYARD_DELICACY_SOMEWHERE,
    SP.SPACESHIP_GRAVEYARD_REVENANT,
    SP.THE_QUASAR_FIELDS_MIN_MAXING,
    SP.PRISON_BREAKOUT_HANGING_JUDGE,
    SP.DAMS_EDGE_HYDRANO_OFFENSIVE_DRIVER,
    SP.DAMS_EDGE_HYDRANO_RING_AROUND_THE_ROSIE,
    SP.A_FICTION_FULL_OF_DOLLARS_PERFECT_MIRROR,
    SP.BULKHEAD_LOCK_CEREAL_DECODER_RING,
    SP.UNDERWATER_BUNKER_LEET_HAXXOR,
    SP.UNDERWATER_BUNKER_IM_NOT_THERE,
})

SKILL_POINT_DIFFICULTY: dict[str, SkillPointDifficulty] = {
    **dict.fromkeys(EASY_SKILL_POINTS, SkillPointDifficulty.EASY),
    **dict.fromkeys(HARD_SKILL_POINTS, SkillPointDifficulty.HARD),
}

# Operatives a skill point needs besides its own case's. The casino rhythm
# mission embeds Gadgetbot combat sections.
EXTRA_SKILL_POINT_OPERATIVES: dict[str, frozenset[str]] = {
    SP.HIGH_STAKES_ROOM_GADGEBOT_STANDS_ALONE: frozenset({SACOperatives.GADGETBOTS}),
}
