"""CaseStructure: a single per-case, bit-flag-tracked location -- pairs a
short event title with its Case, memory address and completion bit. Every
per-case constants module (missions, cutscenes, gadgetbot/special/ratchet
challenges, skill points) builds a flat tuple of these instead of each
hand-typing its own full "Case: Category: Title" string, which is how the
old convention drifted (e.g. cutscenes.py's "Entere" typos) -- the full
display/AP location name is generated by __str__ instead.

operative is deliberately NOT a field here: it's derived from case_name via
constants/planets.py's CASE_NAME_TO_OPERATIVE, the single source of truth
for which operative a case belongs to (see locations.py's SACLocationData
comment) -- typing it out per-entry would just be the same "can drift out
of sync" problem this replaces.

event_flag/event_address default to 0, meaning "not confirmed live yet" --
lets a CaseStructure be declared as soon as the event's name (and ideally
its case) is known, ahead of address confirmation, same as the old
per-category address dicts let name lists get ahead of addresses. Every
core/*.py Inventory built on top of these (see core/case_events.py) must
skip event_address == 0 entries rather than actually read address 0.

case_name itself may also be a "TODO" placeholder (not a real SACCases
value) for locations whose case isn't known yet -- CASE_NAME_TO_OPERATIVE.get()
falls back to case_name itself in that case, rather than raising, so an
unfinished entry still constructs and just prints an obviously-unfinished
name (e.g. "TODO: TODO: Some Mission") instead of crashing on import."""
from dataclasses import dataclass

from .planets import CASE_NAME_TO_OPERATIVE


@dataclass(frozen=True)
class CaseStructure:
    case_name: str          # SACCases constant (or "TODO" if not yet known)
    event_name: str         # short title -- the one part every entry must hand-type
    category: str = ""      # e.g. "Gadgetbot Challenge", "Skill Point" -- "" for missions/cutscenes
    event_flag: int = 0      # bitmask within event_address's byte; 0 = not confirmed live yet
    event_address: int = 0   # 0 = not confirmed live yet

    @property
    def operative(self) -> str:
        return CASE_NAME_TO_OPERATIVE.get(self.case_name, self.case_name)

    def check_flag(self, flag_value: int) -> bool:
        """Check if this event's completion bit is set in the given byte."""
        return bool(flag_value & self.event_flag)

    def __str__(self) -> str:
        middle = f"{self.category}: " if self.category else ""
        return f"{self.operative}: {self.case_name}: {middle}{self.event_name}"


def group_by_case(entries: tuple[CaseStructure, ...]) -> dict[str, tuple[str, ...]]:
    """Group a flat tuple of CaseStructure entries into case_name -> tuple
    of full display names, in declaration order -- the shape locations.py's
    *_BY_CASE loops expect (see e.g. GADGETBOT_CHALLENGES_BY_CASE)."""
    by_case: dict[str, list[str]] = {}
    for entry in entries:
        by_case.setdefault(entry.case_name, []).append(str(entry))
    return {case: tuple(names) for case, names in by_case.items()}
