"""Location tables, assembled from one file per case (locations/<case>.py)
-- each case file builds its own locations (5 dicts, grouped by which
options.py toggle/Choice value gates them) using its own fixed id block
(see _shared.py), so this module just imports and merges/re-derives from
them rather than building anything itself. See each case file's own
docstring for its 5-dict breakdown -- the two mission dicts
(*_MISSION_LOCATIONS / *_ALL_MISSIONS_LOCATIONS) are mutually exclusive at
generation time (regions.py picks one set based on options.py's Missions),
but both always exist here so the client's location-name-to-id table
covers every possible name regardless of which mode a given seed used.

NOTE: location ids are assigned per-case-block now (see _shared.py) rather
than by one shared sequential counter walked in category order -- every
existing location's id has changed as a result of this reorg. Names are
unchanged, only ids moved."""
from ..constants import ALIEN_CODES, KEYCARDS
from ..constants.skillpoints import SKILL_POINTS
from ._shared import SACLocationData
from .a_fiction_full_of_dollars import (
    A_FICTION_FULL_OF_DOLLARS_ALL_MISSIONS_LOCATIONS,
    A_FICTION_FULL_OF_DOLLARS_CUTSCENE_LOCATIONS,
    A_FICTION_FULL_OF_DOLLARS_LOCATIONS,
    A_FICTION_FULL_OF_DOLLARS_MISSION_LOCATIONS,
    A_FICTION_FULL_OF_DOLLARS_OTHER_LOCATIONS,
)
from .asyanica_rooftops import (
    ASYANICA_ROOFTOPS_ALL_MISSIONS_LOCATIONS,
    ASYANICA_ROOFTOPS_CUTSCENE_LOCATIONS,
    ASYANICA_ROOFTOPS_LOCATIONS,
    ASYANICA_ROOFTOPS_MISSION_LOCATIONS,
    ASYANICA_ROOFTOPS_OTHER_LOCATIONS,
)
from .azcotal_alley import (
    AZCOTAL_ALLEY_ALL_MISSIONS_LOCATIONS,
    AZCOTAL_ALLEY_CUTSCENE_LOCATIONS,
    AZCOTAL_ALLEY_LOCATIONS,
    AZCOTAL_ALLEY_MISSION_LOCATIONS,
    AZCOTAL_ALLEY_OTHER_LOCATIONS,
)
from .boltaire_gem_wing import (
    BOLTAIRE_GEM_WING_ALL_MISSIONS_LOCATIONS,
    BOLTAIRE_GEM_WING_CUTSCENE_LOCATIONS,
    BOLTAIRE_GEM_WING_LOCATIONS,
    BOLTAIRE_GEM_WING_MISSION_LOCATIONS,
    BOLTAIRE_GEM_WING_OTHER_LOCATIONS,
)
from .boltaire_museum import (
    BOLTAIRE_MUSEUM_ALL_MISSIONS_LOCATIONS,
    BOLTAIRE_MUSEUM_CUTSCENE_LOCATIONS,
    BOLTAIRE_MUSEUM_LOCATIONS,
    BOLTAIRE_MUSEUM_MISSION_LOCATIONS,
    BOLTAIRE_MUSEUM_OTHER_LOCATIONS,
)
from .bulkhead_lock import (
    BULKHEAD_LOCK_ALL_MISSIONS_LOCATIONS,
    BULKHEAD_LOCK_CUTSCENE_LOCATIONS,
    BULKHEAD_LOCK_LOCATIONS,
    BULKHEAD_LOCK_MISSION_LOCATIONS,
    BULKHEAD_LOCK_OTHER_LOCATIONS,
)
from .countess_villa import (
    COUNTESS_VILLA_ALL_MISSIONS_LOCATIONS,
    COUNTESS_VILLA_CUTSCENE_LOCATIONS,
    COUNTESS_VILLA_LOCATIONS,
    COUNTESS_VILLA_MISSION_LOCATIONS,
    COUNTESS_VILLA_OTHER_LOCATIONS,
)
from .dams_edge_hydrano import (
    DAMS_EDGE_HYDRANO_ALL_MISSIONS_LOCATIONS,
    DAMS_EDGE_HYDRANO_CUTSCENE_LOCATIONS,
    DAMS_EDGE_HYDRANO_LOCATIONS,
    DAMS_EDGE_HYDRANO_MISSION_LOCATIONS,
    DAMS_EDGE_HYDRANO_OTHER_LOCATIONS,
)
from .galactic_bolt_reserve import (
    GALACTIC_BOLT_RESERVE_ALL_MISSIONS_LOCATIONS,
    GALACTIC_BOLT_RESERVE_CUTSCENE_LOCATIONS,
    GALACTIC_BOLT_RESERVE_LOCATIONS,
    GALACTIC_BOLT_RESERVE_MISSION_LOCATIONS,
    GALACTIC_BOLT_RESERVE_OTHER_LOCATIONS,
)
from .glaciara_ski_slopes import (
    GLACIARA_SKI_SLOPES_ALL_MISSIONS_LOCATIONS,
    GLACIARA_SKI_SLOPES_CUTSCENE_LOCATIONS,
    GLACIARA_SKI_SLOPES_LOCATIONS,
    GLACIARA_SKI_SLOPES_MISSION_LOCATIONS,
    GLACIARA_SKI_SLOPES_OTHER_LOCATIONS,
)
from .gondola_ascent import (
    GONDOLA_ASCENT_ALL_MISSIONS_LOCATIONS,
    GONDOLA_ASCENT_CUTSCENE_LOCATIONS,
    GONDOLA_ASCENT_LOCATIONS,
    GONDOLA_ASCENT_MISSION_LOCATIONS,
    GONDOLA_ASCENT_OTHER_LOCATIONS,
)
from .high_rollers_casino import (
    HIGH_ROLLERS_CASINO_ALL_MISSIONS_LOCATIONS,
    HIGH_ROLLERS_CASINO_CUTSCENE_LOCATIONS,
    HIGH_ROLLERS_CASINO_LOCATIONS,
    HIGH_ROLLERS_CASINO_MISSION_LOCATIONS,
    HIGH_ROLLERS_CASINO_OTHER_LOCATIONS,
)
from .high_stakes_room import (
    HIGH_STAKES_ROOM_ALL_MISSIONS_LOCATIONS,
    HIGH_STAKES_ROOM_CUTSCENE_LOCATIONS,
    HIGH_STAKES_ROOM_LOCATIONS,
    HIGH_STAKES_ROOM_MISSION_LOCATIONS,
    HIGH_STAKES_ROOM_OTHER_LOCATIONS,
)
from .inside_the_a_eye import (
    INSIDE_THE_A_EYE_ALL_MISSIONS_LOCATIONS,
    INSIDE_THE_A_EYE_CUTSCENE_LOCATIONS,
    INSIDE_THE_A_EYE_LOCATIONS,
    INSIDE_THE_A_EYE_MISSION_LOCATIONS,
    INSIDE_THE_A_EYE_OTHER_LOCATIONS,
)
from .klunks_lair import (
    KLUNKS_LAIR_ALL_MISSIONS_LOCATIONS,
    KLUNKS_LAIR_CUTSCENE_LOCATIONS,
    KLUNKS_LAIR_LOCATIONS,
    KLUNKS_LAIR_MISSION_LOCATIONS,
    KLUNKS_LAIR_OTHER_LOCATIONS,
)
from .larger_than_life import (
    LARGER_THAN_LIFE_ALL_MISSIONS_LOCATIONS,
    LARGER_THAN_LIFE_CUTSCENE_LOCATIONS,
    LARGER_THAN_LIFE_LOCATIONS,
    LARGER_THAN_LIFE_MISSION_LOCATIONS,
    LARGER_THAN_LIFE_OTHER_LOCATIONS,
)
from .madam_butterqwark import (
    MADAM_BUTTERQWARK_ALL_MISSIONS_LOCATIONS,
    MADAM_BUTTERQWARK_CUTSCENE_LOCATIONS,
    MADAM_BUTTERQWARK_LOCATIONS,
    MADAM_BUTTERQWARK_MISSION_LOCATIONS,
    MADAM_BUTTERQWARK_OTHER_LOCATIONS,
)
from .max_security_cells import (
    MAX_SECURITY_CELLS_ALL_MISSIONS_LOCATIONS,
    MAX_SECURITY_CELLS_CUTSCENE_LOCATIONS,
    MAX_SECURITY_CELLS_LOCATIONS,
    MAX_SECURITY_CELLS_MISSION_LOCATIONS,
    MAX_SECURITY_CELLS_OTHER_LOCATIONS,
)
from .prison_breakout import (
    PRISON_BREAKOUT_ALL_MISSIONS_LOCATIONS,
    PRISON_BREAKOUT_CUTSCENE_LOCATIONS,
    PRISON_BREAKOUT_LOCATIONS,
    PRISON_BREAKOUT_MISSION_LOCATIONS,
    PRISON_BREAKOUT_OTHER_LOCATIONS,
)
from .rooftop_deathtrap import (
    ROOFTOP_DEATHTRAP_ALL_MISSIONS_LOCATIONS,
    ROOFTOP_DEATHTRAP_CUTSCENE_LOCATIONS,
    ROOFTOP_DEATHTRAP_LOCATIONS,
    ROOFTOP_DEATHTRAP_MISSION_LOCATIONS,
    ROOFTOP_DEATHTRAP_OTHER_LOCATIONS,
)
from .saint_qwark import (
    SAINT_QWARK_ALL_MISSIONS_LOCATIONS,
    SAINT_QWARK_CUTSCENE_LOCATIONS,
    SAINT_QWARK_LOCATIONS,
    SAINT_QWARK_MISSION_LOCATIONS,
    SAINT_QWARK_OTHER_LOCATIONS,
)
from .spaceship_graveyard import (
    SPACESHIP_GRAVEYARD_ALL_MISSIONS_LOCATIONS,
    SPACESHIP_GRAVEYARD_CUTSCENE_LOCATIONS,
    SPACESHIP_GRAVEYARD_LOCATIONS,
    SPACESHIP_GRAVEYARD_MISSION_LOCATIONS,
    SPACESHIP_GRAVEYARD_OTHER_LOCATIONS,
)
from .suck_and_jive import (
    SUCK_AND_JIVE_ALL_MISSIONS_LOCATIONS,
    SUCK_AND_JIVE_CUTSCENE_LOCATIONS,
    SUCK_AND_JIVE_LOCATIONS,
    SUCK_AND_JIVE_MISSION_LOCATIONS,
    SUCK_AND_JIVE_OTHER_LOCATIONS,
)
from .the_exercise_yard import (
    THE_EXERCISE_YARD_ALL_MISSIONS_LOCATIONS,
    THE_EXERCISE_YARD_CUTSCENE_LOCATIONS,
    THE_EXERCISE_YARD_LOCATIONS,
    THE_EXERCISE_YARD_MISSION_LOCATIONS,
    THE_EXERCISE_YARD_OTHER_LOCATIONS,
)
from .the_mess_hall import (
    THE_MESS_HALL_ALL_MISSIONS_LOCATIONS,
    THE_MESS_HALL_CUTSCENE_LOCATIONS,
    THE_MESS_HALL_LOCATIONS,
    THE_MESS_HALL_MISSION_LOCATIONS,
    THE_MESS_HALL_OTHER_LOCATIONS,
)
from .the_quasar_fields import (
    THE_QUASAR_FIELDS_ALL_MISSIONS_LOCATIONS,
    THE_QUASAR_FIELDS_CUTSCENE_LOCATIONS,
    THE_QUASAR_FIELDS_LOCATIONS,
    THE_QUASAR_FIELDS_MISSION_LOCATIONS,
    THE_QUASAR_FIELDS_OTHER_LOCATIONS,
)
from .the_showers import (
    THE_SHOWERS_ALL_MISSIONS_LOCATIONS,
    THE_SHOWERS_CUTSCENE_LOCATIONS,
    THE_SHOWERS_LOCATIONS,
    THE_SHOWERS_MISSION_LOCATIONS,
    THE_SHOWERS_OTHER_LOCATIONS,
)
from .underwater_bunker import (
    UNDERWATER_BUNKER_ALL_MISSIONS_LOCATIONS,
    UNDERWATER_BUNKER_CUTSCENE_LOCATIONS,
    UNDERWATER_BUNKER_LOCATIONS,
    UNDERWATER_BUNKER_MISSION_LOCATIONS,
    UNDERWATER_BUNKER_OTHER_LOCATIONS,
)
from .venantonio_canals import (
    VENANTONIO_CANALS_ALL_MISSIONS_LOCATIONS,
    VENANTONIO_CANALS_CUTSCENE_LOCATIONS,
    VENANTONIO_CANALS_LOCATIONS,
    VENANTONIO_CANALS_MISSION_LOCATIONS,
    VENANTONIO_CANALS_OTHER_LOCATIONS,
)
from .venantonio_labs import (
    VENANTONIO_LABS_ALL_MISSIONS_LOCATIONS,
    VENANTONIO_LABS_CUTSCENE_LOCATIONS,
    VENANTONIO_LABS_LOCATIONS,
    VENANTONIO_LABS_MISSION_LOCATIONS,
    VENANTONIO_LABS_OTHER_LOCATIONS,
)

# (always-on, mission, all_missions, cutscene, other) per case -- case_id order.
_CASES: tuple[tuple[dict[str, SACLocationData], ...], ...] = (
    (BOLTAIRE_MUSEUM_LOCATIONS, BOLTAIRE_MUSEUM_MISSION_LOCATIONS, BOLTAIRE_MUSEUM_ALL_MISSIONS_LOCATIONS,
     BOLTAIRE_MUSEUM_CUTSCENE_LOCATIONS, BOLTAIRE_MUSEUM_OTHER_LOCATIONS),
    (BOLTAIRE_GEM_WING_LOCATIONS, BOLTAIRE_GEM_WING_MISSION_LOCATIONS, BOLTAIRE_GEM_WING_ALL_MISSIONS_LOCATIONS,
     BOLTAIRE_GEM_WING_CUTSCENE_LOCATIONS, BOLTAIRE_GEM_WING_OTHER_LOCATIONS),
    (MAX_SECURITY_CELLS_LOCATIONS, MAX_SECURITY_CELLS_MISSION_LOCATIONS, MAX_SECURITY_CELLS_ALL_MISSIONS_LOCATIONS,
     MAX_SECURITY_CELLS_CUTSCENE_LOCATIONS, MAX_SECURITY_CELLS_OTHER_LOCATIONS),
    (ROOFTOP_DEATHTRAP_LOCATIONS, ROOFTOP_DEATHTRAP_MISSION_LOCATIONS, ROOFTOP_DEATHTRAP_ALL_MISSIONS_LOCATIONS,
     ROOFTOP_DEATHTRAP_CUTSCENE_LOCATIONS, ROOFTOP_DEATHTRAP_OTHER_LOCATIONS),
    (ASYANICA_ROOFTOPS_LOCATIONS, ASYANICA_ROOFTOPS_MISSION_LOCATIONS, ASYANICA_ROOFTOPS_ALL_MISSIONS_LOCATIONS,
     ASYANICA_ROOFTOPS_CUTSCENE_LOCATIONS, ASYANICA_ROOFTOPS_OTHER_LOCATIONS),
    (LARGER_THAN_LIFE_LOCATIONS, LARGER_THAN_LIFE_MISSION_LOCATIONS, LARGER_THAN_LIFE_ALL_MISSIONS_LOCATIONS,
     LARGER_THAN_LIFE_CUTSCENE_LOCATIONS, LARGER_THAN_LIFE_OTHER_LOCATIONS),
    (COUNTESS_VILLA_LOCATIONS, COUNTESS_VILLA_MISSION_LOCATIONS, COUNTESS_VILLA_ALL_MISSIONS_LOCATIONS,
     COUNTESS_VILLA_CUTSCENE_LOCATIONS, COUNTESS_VILLA_OTHER_LOCATIONS),
    (GLACIARA_SKI_SLOPES_LOCATIONS, GLACIARA_SKI_SLOPES_MISSION_LOCATIONS, GLACIARA_SKI_SLOPES_ALL_MISSIONS_LOCATIONS,
     GLACIARA_SKI_SLOPES_CUTSCENE_LOCATIONS, GLACIARA_SKI_SLOPES_OTHER_LOCATIONS),
    (THE_MESS_HALL_LOCATIONS, THE_MESS_HALL_MISSION_LOCATIONS, THE_MESS_HALL_ALL_MISSIONS_LOCATIONS,
     THE_MESS_HALL_CUTSCENE_LOCATIONS, THE_MESS_HALL_OTHER_LOCATIONS),
    (AZCOTAL_ALLEY_LOCATIONS, AZCOTAL_ALLEY_MISSION_LOCATIONS, AZCOTAL_ALLEY_ALL_MISSIONS_LOCATIONS,
     AZCOTAL_ALLEY_CUTSCENE_LOCATIONS, AZCOTAL_ALLEY_OTHER_LOCATIONS),
    (GONDOLA_ASCENT_LOCATIONS, GONDOLA_ASCENT_MISSION_LOCATIONS, GONDOLA_ASCENT_ALL_MISSIONS_LOCATIONS,
     GONDOLA_ASCENT_CUTSCENE_LOCATIONS, GONDOLA_ASCENT_OTHER_LOCATIONS),
    (SUCK_AND_JIVE_LOCATIONS, SUCK_AND_JIVE_MISSION_LOCATIONS, SUCK_AND_JIVE_ALL_MISSIONS_LOCATIONS,
     SUCK_AND_JIVE_CUTSCENE_LOCATIONS, SUCK_AND_JIVE_OTHER_LOCATIONS),
    (HIGH_ROLLERS_CASINO_LOCATIONS, HIGH_ROLLERS_CASINO_MISSION_LOCATIONS, HIGH_ROLLERS_CASINO_ALL_MISSIONS_LOCATIONS,
     HIGH_ROLLERS_CASINO_CUTSCENE_LOCATIONS, HIGH_ROLLERS_CASINO_OTHER_LOCATIONS),
    (THE_EXERCISE_YARD_LOCATIONS, THE_EXERCISE_YARD_MISSION_LOCATIONS, THE_EXERCISE_YARD_ALL_MISSIONS_LOCATIONS,
     THE_EXERCISE_YARD_CUTSCENE_LOCATIONS, THE_EXERCISE_YARD_OTHER_LOCATIONS),
    (HIGH_STAKES_ROOM_LOCATIONS, HIGH_STAKES_ROOM_MISSION_LOCATIONS, HIGH_STAKES_ROOM_ALL_MISSIONS_LOCATIONS,
     HIGH_STAKES_ROOM_CUTSCENE_LOCATIONS, HIGH_STAKES_ROOM_OTHER_LOCATIONS),
    (VENANTONIO_LABS_LOCATIONS, VENANTONIO_LABS_MISSION_LOCATIONS, VENANTONIO_LABS_ALL_MISSIONS_LOCATIONS,
     VENANTONIO_LABS_CUTSCENE_LOCATIONS, VENANTONIO_LABS_OTHER_LOCATIONS),
    (VENANTONIO_CANALS_LOCATIONS, VENANTONIO_CANALS_MISSION_LOCATIONS, VENANTONIO_CANALS_ALL_MISSIONS_LOCATIONS,
     VENANTONIO_CANALS_CUTSCENE_LOCATIONS, VENANTONIO_CANALS_OTHER_LOCATIONS),
    (MADAM_BUTTERQWARK_LOCATIONS, MADAM_BUTTERQWARK_MISSION_LOCATIONS, MADAM_BUTTERQWARK_ALL_MISSIONS_LOCATIONS,
     MADAM_BUTTERQWARK_CUTSCENE_LOCATIONS, MADAM_BUTTERQWARK_OTHER_LOCATIONS),
    (GALACTIC_BOLT_RESERVE_LOCATIONS, GALACTIC_BOLT_RESERVE_MISSION_LOCATIONS, GALACTIC_BOLT_RESERVE_ALL_MISSIONS_LOCATIONS,
     GALACTIC_BOLT_RESERVE_CUTSCENE_LOCATIONS, GALACTIC_BOLT_RESERVE_OTHER_LOCATIONS),
    (INSIDE_THE_A_EYE_LOCATIONS, INSIDE_THE_A_EYE_MISSION_LOCATIONS, INSIDE_THE_A_EYE_ALL_MISSIONS_LOCATIONS,
     INSIDE_THE_A_EYE_CUTSCENE_LOCATIONS, INSIDE_THE_A_EYE_OTHER_LOCATIONS),
    (THE_SHOWERS_LOCATIONS, THE_SHOWERS_MISSION_LOCATIONS, THE_SHOWERS_ALL_MISSIONS_LOCATIONS,
     THE_SHOWERS_CUTSCENE_LOCATIONS, THE_SHOWERS_OTHER_LOCATIONS),
    (SPACESHIP_GRAVEYARD_LOCATIONS, SPACESHIP_GRAVEYARD_MISSION_LOCATIONS, SPACESHIP_GRAVEYARD_ALL_MISSIONS_LOCATIONS,
     SPACESHIP_GRAVEYARD_CUTSCENE_LOCATIONS, SPACESHIP_GRAVEYARD_OTHER_LOCATIONS),
    (SAINT_QWARK_LOCATIONS, SAINT_QWARK_MISSION_LOCATIONS, SAINT_QWARK_ALL_MISSIONS_LOCATIONS,
     SAINT_QWARK_CUTSCENE_LOCATIONS, SAINT_QWARK_OTHER_LOCATIONS),
    (THE_QUASAR_FIELDS_LOCATIONS, THE_QUASAR_FIELDS_MISSION_LOCATIONS, THE_QUASAR_FIELDS_ALL_MISSIONS_LOCATIONS,
     THE_QUASAR_FIELDS_CUTSCENE_LOCATIONS, THE_QUASAR_FIELDS_OTHER_LOCATIONS),
    (PRISON_BREAKOUT_LOCATIONS, PRISON_BREAKOUT_MISSION_LOCATIONS, PRISON_BREAKOUT_ALL_MISSIONS_LOCATIONS,
     PRISON_BREAKOUT_CUTSCENE_LOCATIONS, PRISON_BREAKOUT_OTHER_LOCATIONS),
    (DAMS_EDGE_HYDRANO_LOCATIONS, DAMS_EDGE_HYDRANO_MISSION_LOCATIONS, DAMS_EDGE_HYDRANO_ALL_MISSIONS_LOCATIONS,
     DAMS_EDGE_HYDRANO_CUTSCENE_LOCATIONS, DAMS_EDGE_HYDRANO_OTHER_LOCATIONS),
    (A_FICTION_FULL_OF_DOLLARS_LOCATIONS, A_FICTION_FULL_OF_DOLLARS_MISSION_LOCATIONS, A_FICTION_FULL_OF_DOLLARS_ALL_MISSIONS_LOCATIONS,
     A_FICTION_FULL_OF_DOLLARS_CUTSCENE_LOCATIONS, A_FICTION_FULL_OF_DOLLARS_OTHER_LOCATIONS),
    (BULKHEAD_LOCK_LOCATIONS, BULKHEAD_LOCK_MISSION_LOCATIONS, BULKHEAD_LOCK_ALL_MISSIONS_LOCATIONS,
     BULKHEAD_LOCK_CUTSCENE_LOCATIONS, BULKHEAD_LOCK_OTHER_LOCATIONS),
    (UNDERWATER_BUNKER_LOCATIONS, UNDERWATER_BUNKER_MISSION_LOCATIONS, UNDERWATER_BUNKER_ALL_MISSIONS_LOCATIONS,
     UNDERWATER_BUNKER_CUTSCENE_LOCATIONS, UNDERWATER_BUNKER_OTHER_LOCATIONS),
    (KLUNKS_LAIR_LOCATIONS, KLUNKS_LAIR_MISSION_LOCATIONS, KLUNKS_LAIR_ALL_MISSIONS_LOCATIONS,
     KLUNKS_LAIR_CUTSCENE_LOCATIONS, KLUNKS_LAIR_OTHER_LOCATIONS),
)

ALWAYS_ON_LOCATIONS: dict[str, SACLocationData] = {}
STORY_MISSION_LOCATIONS: dict[str, SACLocationData] = {}
ALL_STORY_MISSION_LOCATIONS: dict[str, SACLocationData] = {}
CUTSCENE_LOCATIONS: dict[str, SACLocationData] = {}
_OTHER_LOCATIONS: dict[str, SACLocationData] = {}
for _always_on, _mission, _all_missions, _cutscene, _other in _CASES:
    ALWAYS_ON_LOCATIONS.update(_always_on)
    STORY_MISSION_LOCATIONS.update(_mission)
    ALL_STORY_MISSION_LOCATIONS.update(_all_missions)
    CUTSCENE_LOCATIONS.update(_cutscene)
    _OTHER_LOCATIONS.update(_other)
del _always_on, _mission, _all_missions, _cutscene, _other

# _OTHER_LOCATIONS mixes 3 independently-toggleable categories (see each
# case file's docstring) -- split back out by exact display name against
# constants/*.py (CaseStructure.__str__ is what generated these names in
# the first place, so this is a lookup, not a second construction pass).
# The id always comes from _OTHER_LOCATIONS (the case files, single source
# of truth) -- only the category-membership decision comes from here.
_SKILL_POINT_NAMES = {str(entry) for entry in SKILL_POINTS}
_KEYCARD_NAMES = {str(entry) for entry in KEYCARDS if entry.case_name != "TODO"}
_ALIEN_CODE_NAMES = {str(entry) for entry in ALIEN_CODES if entry.case_name != "TODO"}

SKILL_POINT_LOCATIONS: dict[str, SACLocationData] = {
    name: data for name, data in _OTHER_LOCATIONS.items() if name in _SKILL_POINT_NAMES
}
KEYCARD_LOCATIONS: dict[str, SACLocationData] = {
    name: data for name, data in _OTHER_LOCATIONS.items() if name in _KEYCARD_NAMES
}
ALIEN_CODE_LOCATIONS: dict[str, SACLocationData] = {
    name: data for name, data in _OTHER_LOCATIONS.items() if name in _ALIEN_CODE_NAMES
}

from ..constants.planets import CASE_NAME_TO_CASE
from ..constants.titanium_bolts import TITANIUM_BOLT_ENTRIES
from ._shared import BASE_ID, CASE_ID_BLOCK_SIZE

# Reserve the end of each case block; existing location IDs stay unchanged.
TITANIUM_BOLT_LOCATIONS = {
    str(entry): SACLocationData(
        BASE_ID + (CASE_NAME_TO_CASE[entry.case_name].case_id - 1) * CASE_ID_BLOCK_SIZE + 900 + index,
        entry.case_name)
    for (_, index), entry in TITANIUM_BOLT_ENTRIES.items()
}
ALWAYS_ON_LOCATIONS.update(TITANIUM_BOLT_LOCATIONS)

ALL_LOCATIONS: dict[str, SACLocationData] = {
    **ALWAYS_ON_LOCATIONS,
    **STORY_MISSION_LOCATIONS,
    **ALL_STORY_MISSION_LOCATIONS,
    **CUTSCENE_LOCATIONS,
    **_OTHER_LOCATIONS,
}

from ..constants.weapon_progression import TITAN_LOCATIONS

TITAN_VENDOR_LOCATIONS = {
    name: SACLocationData(BASE_ID + 31000 + index, 'Titan Vendor')
    for index, name in enumerate(TITAN_LOCATIONS.values())
}
ALL_LOCATIONS.update(TITAN_VENDOR_LOCATIONS)

from ..constants.weapon_mods import WEAPON_MODS
MOD_VENDOR_LOCATIONS = {
    mod.location: SACLocationData(BASE_ID + 32000 + mod.mod_id, 'Mod Vendor')
    for mod in WEAPON_MODS
}
ALL_LOCATIONS.update(MOD_VENDOR_LOCATIONS)
