"""Every location in Boltaire Museum, each carrying its planet, case and access rule."""
from rule_builder.rules import Has, HasAll, True_

from ..constants import (
    SACAlienCodeLocations,
    SACCases,
    SACClankGadgets,
    SACClankWeapons,
    SACCutsceneLocations,
    SACGadgetPickupLocations,
    SACMissionLocations,
    SACPlanets,
    SACRatchetWeapons,
    SACSkillPointLocations,
    SACTitaniumBoltLocations,
)
from .model import SACLocation, SACLocationType

_PLANET = SACPlanets.BOLTAIRE_MUSEUM
_CASE = SACCases.BOLTAIRE_MUSEUM

_FINISH_MISSION = HasAll(SACClankGadgets.BLACK_OUT_PEN, SACClankWeapons.THROWTIE, SACClankGadgets.JETBOOTS)

LOCATIONS: tuple[SACLocation, ...] = (
    SACLocation(
        SACRatchetWeapons.BLASTER,
        _PLANET,
        _CASE,
        SACLocationType.RATCHET_WEAPON,
        77_800_000,
        lambda world: Has(SACClankGadgets.BLACK_OUT_PEN),
    ),
    SACLocation(
        SACClankWeapons.THROWTIE,
        _PLANET,
        _CASE,
        SACLocationType.CLANK_WEAPON,
        77_800_001,
        lambda world: True_(),
    ),
    SACLocation(
        SACClankGadgets.JETBOOTS,
        _PLANET,
        _CASE,
        SACLocationType.CLANK_GADGET,
        77_800_002,
        lambda world: _FINISH_MISSION,
    ),
    SACLocation(
        SACClankGadgets.BLACK_OUT_PEN,
        _PLANET,
        _CASE,
        SACLocationType.CLANK_GADGET,
        77_800_005,
    ),
    SACLocation(
        SACClankGadgets.THERM_OPTIC_SHADES,
        _PLANET,
        _CASE,
        SACLocationType.CLANK_GADGET,
        77_800_006,
    ),
    SACLocation(
        SACGadgetPickupLocations.BOLTAIRE_MUSEUM_BLACK_OUT_PEN,
        _PLANET,
        _CASE,
        SACLocationType.GADGET_PICKUP,
        77_800_007,
        lambda world: True_(),
    ),
    SACLocation(
        SACGadgetPickupLocations.BOLTAIRE_MUSEUM_THERM_OPTIC_SHADES,
        _PLANET,
        _CASE,
        SACLocationType.GADGET_PICKUP,
        77_800_008,
        lambda world: True_(),
    ),
    SACLocation(
        SACTitaniumBoltLocations.BOLTAIRE_MUSEUM_1,
        _PLANET,
        _CASE,
        SACLocationType.TITANIUM_BOLT,
        77_800_901,
        lambda world: Has(SACClankGadgets.JETBOOTS),
    ),
    SACLocation(
        SACTitaniumBoltLocations.BOLTAIRE_MUSEUM_2,
        _PLANET,
        _CASE,
        SACLocationType.TITANIUM_BOLT,
        77_800_902,
        lambda world: HasAll(SACClankGadgets.JETBOOTS, SACClankGadgets.BLACK_OUT_PEN),
    ),
    SACLocation(
        SACMissionLocations.BOLTAIRE_MUSEUM_COMPLETE,
        _PLANET,
        _CASE,
        SACLocationType.CASE_COMPLETE,
        77_800_009,
        lambda world: True_(),
    ),
    SACLocation(
        SACMissionLocations.BOLTAIRE_MUSEUM_ESCAPE_THE_RAVINE,
        _PLANET,
        _CASE,
        SACLocationType.MISSION,
        77_800_010,
        lambda world: True_(),
    ),
    SACLocation(
        SACMissionLocations.BOLTAIRE_MUSEUM_GET_INSIDE_THE_MUSEUM,
        _PLANET,
        _CASE,
        SACLocationType.MISSION,
        77_800_011,
        lambda world: True_(),
    ),
    SACLocation(
        SACMissionLocations.BOLTAIRE_MUSEUM_NOT_THE_GUIDED_TOUR,
        _PLANET,
        _CASE,
        SACLocationType.MISSION,
        77_800_012,
        lambda world: _FINISH_MISSION,
    ),
    SACLocation(
        SACSkillPointLocations.BOLTAIRE_MUSEUM_FURIOUS_FISTS,
        _PLANET,
        _CASE,
        SACLocationType.SKILL_POINT,
        77_800_014,
        lambda world: _FINISH_MISSION,
    ),
    SACLocation(
        SACSkillPointLocations.BOLTAIRE_MUSEUM_SILENT_NIGHT,
        _PLANET,
        _CASE,
        SACLocationType.SKILL_POINT,
        77_800_015,
        lambda world: _FINISH_MISSION,
    ),
    SACLocation(
        SACCutsceneLocations.BOLTAIRE_MUSEUM_ENTER_CUTSCENE,
        _PLANET,
        _CASE,
        SACLocationType.CUTSCENE,
        77_800_013,
        lambda world: True_(),
    ),
    SACLocation(
        SACAlienCodeLocations.BOLTAIRE_MUSEUM_THE_LEGENDS,
        _PLANET,
        _CASE,
        SACLocationType.ALIEN_CODE,
        77_800_016,
        lambda world: Has(SACClankGadgets.THERM_OPTIC_SHADES),
    ),
    SACLocation(
        SACAlienCodeLocations.BOLTAIRE_MUSEUM_RONNS_SECRET,
        _PLANET,
        _CASE,
        SACLocationType.ALIEN_CODE,
        77_800_017,
        lambda world: _FINISH_MISSION & Has(SACClankGadgets.THERM_OPTIC_SHADES),
    ),
    SACLocation(
        SACAlienCodeLocations.BOLTAIRE_MUSEUM_BENS_SECRET,
        _PLANET,
        _CASE,
        SACLocationType.ALIEN_CODE,
        77_800_018,
        lambda world: _FINISH_MISSION & Has(SACClankGadgets.THERM_OPTIC_SHADES),
    ),
)
